"""
MCPBase - A Minimal Yet Structured MCP Server Framework
=======================================================

A production-ready Model Context Protocol (MCP) server implementation with 
clean separation of concerns and modular architecture.

Author: Generated by AI
Version: 1.0.0
License: MIT
"""

__version__ = "1.0.0"
__author__ = "MCPBase Team"
__license__ = "MIT"

from .server import MCPBaseServer

__all__ = ["MCPBaseServer"]